### ISSUE TITLE
Plugin not work on 14.1.3

### ISSUE THREAD

**Issue by tsangwailam** [jaumard/intellij-sails-ide#1]
Just install the Sails plug-in from within the Intellij plugin page. But seem not working, there no options to create Sails project in the new project page. Check the plugin install properly and no error.

OS: Mac 10.10.3
Intellij Ultimate 14.1.3

**Comment by jaumard** [comment]
Hi,

I have same configuration as you
> OS: Mac 10.10.3
> Intellij Ultimate 14.1.3
> 
And I have this : 


You don’t have it ? 

Regards
Jim

**Comment by tsangwailam** [comment]
I check the plugin should install correctly. But there no options for Sails in new project. Try uninstall/restart and no luck. Don't know why. 

Any dependency plugin needed? How can i check the problem?

**Comment by jaumard** [comment]
Hello,

Did you install it with zip file or directly from IntelliJ plugin
repositories ?
I don’t understand why you don’t have it… Normally if the plugin crash,
intelliJ disable the plugin and tell you there a problem.
To use it you need to have NodeJS and JavaScript (already install in paid
version of intellij) modules. Do you have this dependencies install ?


2015-05-21 15:46 GMT+02:00 Siulam <notifications@github.com>:

**Comment by tsangwailam** [comment]
i install directly from intellij plugin page. No error at all. Try on other mac with same os and intellij but still no luck.

i will try install from file later on. hope it help.

**Comment by tsangwailam** [comment]
Try from zip file. No luck.

Any thing i can do to check the problem?

**Comment by tsangwailam** [comment]
I check the log and have the errors.

ERROR - ctionSystem.DefaultActionGroup - Null child action in group New () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=sails.generate_more 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)


ERROR - ctionSystem.DefaultActionGroup - Can't unstub Sails item (Generate new Item) 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:314)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1310)

**Comment by jaumard** [comment]
Hello,

Thanks for the log ! I don’t know why you have this error, I will search and try to correct it. 
I also ask for some help for your problem here https://devnet.jetbrains.com/thread/464375 <https://devnet.jetbrains.com/thread/464375> if you want to follow. 

Regards
Jim

**Comment by udanpe** [comment]
Mac OS 10.10.4
PhpStorm 8.0.3
Not work too

**Comment by warpedgeoid** [comment]
Any movement on this? I just purchased IntelliJ and upgraded from my older trial version and now I'm getting this error. I'm new to IntelliJ and its plugins, but I'm happy to send you logs or anything else that might prove useful.
